// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrikgpsuakavbckouczg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yaWtncHN1YWthdmJja291Y3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0Njc4NDQsImV4cCI6MjA1MzA0Mzg0NH0.8NFBf_4Bkq2m-3g60mNGl8q_u8u0W-hXJ6yndezqq8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});